### ISSUE TITLE
Doesn't work with Browserify

### ISSUE THREAD

**Issue by Haemoglobin** [bvaughn/redux-devtools-filterable-log-monitor#13] opened 2015-12-24 13:58 UTC
Hi, 

Unfortunately it's not possible to use this with browserify as you get the following error during bundling: 

Error: Cannot find module ‘!!./../../node_modules/css-loader/index.js?modules&importLoaders=1!./../../node_modules/cssnext-loader/index.js!./FilterHeader.css’ from ‘c:\dev....\node_modules\redux-devtools-filterable-log-monitor\dist’

**Comment by bvaughn** [comment] 2015-12-26 15:59
Hi @Haemoglobin,

I'm a Webpack user myself so I don't have any immediate suggestions. Perhaps you could share a skeleton project with me that uses Browserify and reproduces this problem? I'd be happy to take a look.

**Comment by bvaughn** [comment] 2015-12-30 16:52
Are you importing CSS files elsewhere in your project? If so, which CSS loader are you using? (Something like [insert-css](https://npmjs.org/package/insert-css) or [npm-css](https://www.npmjs.com/package/npm-css)?)

**Comment by Haemoglobin** [comment] 2015-12-30 21:50
Hey, since I raised the bug I've converted my project over to webpack and it's working fine now. I wasn't doing anything fancy with CSS so had no CSS loader.

Maybe to have it work for browserify the CSS should be inlined into the JavaScript bundle so it doesn't need a plugin to include it as part of the parent app's build? Not a blocker for me now anyways, great dev tool - thanks!

**Comment by Haemoglobin** [comment] 2015-12-30 21:53
P.s I had to install a Object.values polyfill to get it going as that was breaking when I selected the "values" filtering

**Comment by bvaughn** [comment] 2015-12-30 21:55
Happy to hear you've got things working! :)

I have considered inlining the CSS but I have mixed feelings about it. Still that seems to be what some of the other similar projects are doing (like `react-json-tree`) so maybe I should just make the switch too.

Thanks for mentioning the `Object.values` issue you encountered as well.

I'm going to close this issue and create 2 others (for inlining the styles and fixing `Object.values`).

**Closed as completed by bvaughn** 2015-12-30 21:55 UTC
Labels: bug, help wanted
