### ISSUE TITLE
Update dependencies (React 16) 

### ISSUE THREAD

**Issue by edtoken** [bvaughn/redux-devtools-filterable-log-monitor#39] opened 2017-12-13 16:27 UTC
Hello!
After we roll out the update dependecies from issue [#38](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/issues/38) 
I would like to update the dependencies and fixes to React16.

This is issue for pull request :)

**Comment by MutableLoss** [comment] 2017-12-17 23:00
Yay! It will be so satisfying to never see those warning messages again. 👍

**Comment by bvaughn** [comment] 2017-12-18 02:29
I believe the only thing _required_ is to update the `peerDependencies` block to also support React 16, no? This project doesn't _actually_ install React for you. It defers that to your project.

**Comment by bvaughn** [comment] 2017-12-18 02:48
Actually I guess this is incorrect, since both `react-highlighter` and `react-responsive` require updates to properly handle the split-off `prop-types` used in React 16.

**Comment by bvaughn** [comment] 2017-12-18 03:07
It also looks like `react-json-tree` had a style regression between the version that I used previously and the version that supports react 16. ☹️ 

### Before
<img width="430" alt="screen shot 2017-12-17 at 7 06 15 pm" src="https://user-images.githubusercontent.com/29597/34088318-7669f532-e35d-11e7-8168-06ec184dde1b.png">

### After
<img width="430" alt="screen shot 2017-12-17 at 7 07 05 pm" src="https://user-images.githubusercontent.com/29597/34088323-8024207a-e35d-11e7-83da-3d7045394bed.png">

**Comment by bvaughn** [comment] 2017-12-18 03:11
Updated via faf10d8. Released as 0.8.0.

I don't have time to investigate the style regression but would be happy to accept a PR that fixes it if you'd like to look into it.

**Closed as completed by bvaughn** 2017-12-18 03:11 UTC
